name: Bug report
description: Create a report to help us improve
labels: ["C-bug"]
body:
    - type: dropdown
      attributes:
          label: Component
          description: What component is the bug in?
          multiple: true
          options:
              - op-node
              - op-geth
              - SDK
              - Other (please describe)
      validations:
          required: true
    - type: textarea
      attributes:
          label: Describe the bug
          description: A clear and concise description of what the bug is.
      validations:
          required: true
    - type: textarea
      attributes:
          label: To Reproduce
          placeholder: Steps to reproduce the behavior
    - type: textarea
      attributes:
          label: Expected behavior
          placeholder: A clear and concise description of what you expected to happen
    - type: input
      attributes:
          label: What release/version of the above OP component is this about?
          placeholder: "For example, for op-node, provide the output of op-node --version"
    - type: textarea
      attributes:
          label: Anything else relevant? System specifications? Operating system?
